<?php $name = $this->name; ?>
<?php if (isset($name)) { ?>
Dear <?=$name?><br />
<br />
<?php } ?>
You have requested to have your password reset for your account.<br />
<br />
Please visit this url to reset your password.<br />
<br />
<?php $token = $this->token; ?>
<a href="<?=$this->url('zfcuser/forgot-password/reset-password', ['token' => $token], ['force_canonical' => true])?>"><?=$this->url('zfcuser/forgot-password/reset-password', ['token' => $token], ['force_canonical' => true])?></a><br />
<br />
If you received this email in error, you can safely ignore this email.
