<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Smart Dragon Group')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/sdg-logo.ico'
            ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            ->prependFile($this->basepath('js/script.js'))
            ->prependFile($this->basepath('js/noty/jquery.noty.config.js'))
            ->prependFile($this->basepath('js/noty/jquery.noty.packaged.js'))
            ->prependFile($this->basepath('js/listgroup/listgroup.min.js'))
        ?>
    </head>
    <body class="app">
        <div class="app-header">
        	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand sdg-logo" href="<?= $this->url('home') ?>">
                            <img src="<?= $this->basePath('img/sdg-logo.png') ?>" alt="Smart Dragon Group"/>
                        </a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-left">
                            <li class="navbar-item"><a href="<?= $this->url('home') ?>">Home</a></li>
                            <li class="navbar-item"><a href="<?//= $this->url('product') ?>">Product</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                        	<li class="navbar-item"><a href="<?= $this->url('zfcuser') ?>">Login</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>

        <div class="app-content">
        	<div class="container">

                <?= $this->content ?>

                <hr>
            </div>
        </div>

        <div class="app-footer">
        	<div class="container">
        		<footer>

                    <p>&copy; 2010 - <?= date('Y') ?> Smart Dragon Group. All rights reserved.</p>
                </footer>
        	</div>
        </div>
        <!-- /**
         * The fire() method do
         *     Collect all messages from previous and current request
         *     clear current messages because we will show it
         *     add JS files
         *     add JS notifications
         */ -->
        <?php $this->flashNoty()->fire(); ?>

        <?= $this->inlineScript() ?>
        <script type="text/javascript">
		// $(document).off('.data-api');
        </script>
    </body>
</html>
