<?php $form = $this->form; ?>
<?php echo $this->form()->openTag($form) ?>
    <dl class="zend-form">
        <?php foreach ($form as $element) : ?>
            <?php if ($element->getLabel() != null && !$element instanceof Zend\Form\Element\Button) : ?>
                <dt><?php echo $this->formLabel($element) ?></dt>
            <?php endif ?>
            <dd class="control-form"><?php echo $this->formElement($element) . $this->formElementErrors($element) ?></dd>
        <?php endforeach ?>
    </dl>
<?php if ($this->redirect) : ?>
    <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>">
<?php endif ?>
<?php echo $this->form()->closeTag() ?>