<?php // $this->headscript()->prependFile($this->basepath('js/listgroup/listgroup.min.js')); ?>
<?php // $this->headlink()->prependStylesheet($this->basepath('css/style.css'))?>
<style>
a.list-group-item-action:hover,
a.list-group-item-action:focus {
    color: #fff;
    background-color: #337ab7;
    border-color: #337ab7
}
</style>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title"><?php echo $this->translate('Profile Settings')?></div>
    </div>
    <div class="list-group" id="list-tab" role="tablist">
        <a href="<?php echo $this->url('zfcuser/settings');?>"
            class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" role="tab" aria-controls="profile">
            <?php echo $this->translate('Profile')?>
        </a>
        <a href="<?php echo $this->url('zfcuser/changepassword');?>"
            class="list-group-item list-group-item-action" id="list-account-list" data-toggle="list" role="tab" aria-controls="account">
            <?php echo $this->translate('Account')?>
        </a>
        <a href="<?php echo $this->url('zfcuser/changeemail');?>"
            class="list-group-item list-group-item-action" id="list-email-list" data-toggle="list" role="tab" aria-controls="email">
            <?php echo $this->translate('Email')?>
        </a>
        <a href="#<?php // echo $this->url('zfcuser/changeemail')?>"
            class="list-group-item list-group-item-action" id="list-billing-list" data-toggle="list" role="tab" aria-controls="billing">
            <?php echo $this->translate('Billing')?>
        </a>
        <a href="#<?php // echo $this->url('zfcuser/changeemail')?>"
            class="list-group-item list-group-item-action" id="list-history-list" data-toggle="list" role="tab" aria-controls="history">
            <?php echo $this->translate('History')?>
        </a>
    </div>
</div>
