<div class="panel panel-default">
	<div class="panel-heading">
		<div class="panel-title"><?php echo $this->translate('Profile Settings')?></div>
	</div>
	<div class="list-group" id="list-tab" role="tablist">
		<a href="<?php echo $this->url('zfcuser/settings')?>"
			class="list-group-item list-group-item-action active"
			id="list-home-list" data-toggle="list"
			role="tab" aria-controls="home">

			<?php echo $this->translate('Profile')?>
		</a>
      	<a href="<?php echo $this->url('zfcuser/changepassword')?>"
      		class="list-group-item list-group-item-action"
      		id="list-profile-list" data-toggle="list"
      		role="tab" aria-controls="profile">

      		<?php echo $this->translate('Account')?>
  		</a>
      	<a href="<?php echo $this->url('zfcuser/changeemail')?>"
      		class="list-group-item list-group-item-action"
      		id="list-messages-list" data-toggle="list"
      		role="tab" aria-controls="messages">

      		<?php echo $this->translate('Email')?>
  		</a>
	</div>
</div>