<div class="row">
	<div class="col-md-offset-4 col-md-4 col-sm-offset-3 col-sm-6">
        <h3><?php echo sprintf($this->translate('Change Email for %s'), $this->zfcUserDisplayName()); ?></h3>

        <?php if ($status === true) : ?>
        <div class="alert alert-success"><?php echo $this->translate('Email address changed successfully.'); ?></div>
        <?php elseif ($status === false) : ?>
        <div class="alert alert-danger"><?php echo $this->translate('Unable to update your email address. Please try again.'); ?></div>
        <?php endif; ?>
        <?php

        $form = $this->changeEmailForm;

        $form->prepare();
        $form->setAttribute('action', $this->url('zfcuser/changeemail'));
        $form->setAttribute('method', 'post');
        ?>

        <?php echo $this->partial('_form.phtml', ['form' => $form]); ?>

    </div>
</div>