<?php echo $this->partial('_user.phtml'); ?>

<div class="user-info">
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-4">

                    <?php echo $this->partial('_list.phtml'); ?>

                </div>
                <div class="col-md-8">
                    <div class="title-alias h3">Change Email Address</div>
                    <hr class="title-alias-divider">
                    <div class="user-item-value">
                        <!--
                        <?php $status = $this->status; ?>
                        <?php if ($status === true) : ?>
                        <div class="alert alert-success"><?php echo $this->translate('Email address changed successfully.'); ?></div>
                        <?php elseif ($status === false) : ?>
                        <div class="alert alert-danger"><?php echo $this->translate('Unable to update your email address. Please try again.'); ?></div>
                        <?php endif; ?>
                         -->
                        <?php

                        $form = $this->changeEmailForm;

                        $form->prepare();
                        $form->setAttribute('action', $this->url('zfcuser/changeemail'));
                        $form->setAttribute('method', 'post');
                        ?>

                        <?php echo $this->partial('_form.phtml', ['form' => $form]); ?>

                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">

        </div>
    </div>
</div>
