<div style="float:left; padding-right:10px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
<h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3>
<a href="<?php echo $this->url('zfcuser/logout') ?>"><?php echo $this->translate('Sign Out'); ?></a> |
<a href="<?php echo $this->url('zfcuser/logout') ?>"><?php echo $this->translate('Settings'); ?></a>
<div style="clear:both;"></div>

<div class="user-info">
	<div class="row">
		<div class="col-md-6">
			<div class="panel panel-default">
				<div class="panel-heading">
					<div class="panel-title"><?php echo $this->translate('User Infomation')?></div>
				</div>
				<div class="panel-body">
					<div class="table-responsive">
						<table class="table table-striped table-bordered table-hover">
                          <tr>
                            <td>Id</td>
                            <td><?php echo $this->zfcUserIdentity()->getId() ?></td>
                          </tr>
                          <tr>
                            <td>User name</td>
                            <td><?php echo $this->zfcUserIdentity()->getUserName() ?></td>
                          </tr>
                          <tr>
                            <td>Display name</td>
                            <td><?php echo $this->zfcUserIdentity()->getDisplayName() ?></td>
                          </tr>
                          <tr>
                            <td>Email address</td>
                            <td><?php echo $this->zfcUserIdentity()->getEmail() ?></td>
                          </tr>
                          <tr>
                            <td>Status</td>
                            <td><?php echo $this->zfcUserIdentity()->getState() ?></td>
                          </tr>
                      	</table>
                	</div>
				</div>
			</div>
		</div>
	</div>
</div>
