<?php echo $this->partial('_user.phtml'); ?>

<div class="user-info">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title"><?php echo $this->translate('User Infomation')?></div>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover">
                          <tr>
                            <td><?php echo $this->translate('Id') ?></td>
                            <td><?php echo $this->zfcUserIdentity()->getId() ?></td>
                          </tr>
                          <tr>
                            <td><?php echo $this->translate('User name') ?></td>
                            <td><?php echo $this->zfcUserIdentity()->getUserName() ?></td>
                          </tr>
                          <tr>
                            <td><?php echo $this->translate('Display name') ?></td>
                            <td><?php echo $this->zfcUserIdentity()->getDisplayName() ?></td>
                          </tr>
                          <tr>
                            <td><?php echo $this->translate('Email address') ?></td>
                            <td><?php echo $this->zfcUserIdentity()->getEmail() ?></td>
                          </tr>
                          <tr>
                            <td><?php echo $this->translate('Status') ?></td>
                            <td><?php echo $this->zfcUserIdentity()->getState() ?></td>
                          </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
