<div class="row">
	<div class="col-md-offset-4 col-md-4 col-sm-offset-3 col-sm-6">
		<h1 class="text-center"><?php echo $this->translate('Please Sign In'); ?></h1>

        <?php
        $form = $this->loginForm;
        $form->prepare();
        $form->setAttribute('action', $this->url('zfcuser/login'));
        $form->setAttribute('method', 'post');
        $form->setAttribute('autocomplete', 'off');
        ?>

        <?php /* if ($this->flashMessenger()->setNamespace('zfcuser-login-form')->hasMessages()) :
            $messages = $this->flashMessenger()->setNamespace('zfcuser-login-form')->getMessages();
            foreach ($messages as $message) { */ ?>
                <!-- <div class="alert alert-danger"> -->
                    <?php // echo $message; ?>
                <!-- </div> -->
            <?php //} ?>
        <?php //endif; ?>

        <?php echo $this->partial('_form.phtml', ['form' => $form]); ?>

		<?php // echo $this->translate('Forgot password?')?>
		<!-- <a href="<?php echo $this->url('zfcuser/changepassword') . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>"><?php echo $this->translate('Forgot password?'); ?></a>

		<hr> -->

        <?php if ($this->enableRegistration) : ?>
        <?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
        <?php endif; ?>
	</div>
</div>

