<div class="row">
	<div class="col-md-offset-4 col-md-4 col-sm-offset-3 col-sm-6">
		<h1 class="text-center"><?php echo $this->translate('Please Register'); ?></h1>

        <?php
        if (!$this->enableRegistration) {
            print "Registration is disabled";
            return;
        }
        $form = $this->registerForm;
        $form->prepare();
        $form->setAttribute('action', $this->url('zfcuser/register'));
        $form->setAttribute('method', 'post');
        $form->setAttribute('autocomplete', 'off');
        ?>

        <?php echo $this->partial('_form.phtml', ['form' => $form]); ?>
	</div>
</div>
