<?php echo $this->partial('_user.phtml'); ?>

<div class="user-info">
	<div class="row">
		<div class="col-md-6">
			<div class="row">
				<div class="col-md-4">

            		<?php echo $this->partial('_list.phtml'); ?>

            	</div>
            	<div class="col-md-8">
            		<div class="title-alias h3">Change Profile Name</div>
            		<hr class="title-alias-divider">
            		<div class="user-item-value">
        				<?php

        				$form = $this->settingsForm;

        				$form->prepare();
        				$form->setAttribute('action', $this->url('zfcuser/settings'));
        				$form->setAttribute('method', 'post');
        				$form->setAttribute('autocomplete', 'on');
        				?>

        				<?php echo $this->partial('_form.phtml', ['form' => $form]); ?>

            		</div>
            	</div>
			</div>
		</div>
		<div class="col-md-6">

		</div>
    </div>
</div>
